server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  datasource:
    #ToDo Remove before commit
    url: jdbc:mysql://localhost:3307/authentication
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  jsonWebToken:
    secret: "testfbhsdfhvdfskjdfhg9uorrt743zh7943hzt4uhrtj4jtui4hz4aij498ujthg4zhnawifrkarfhazuuaj4w3e43q08rh43fjfka4fha47hfj4aew8fh4af489r43h4uj4j8r4uik43qa9804hr9ijk48hhoi"
    duration: 43200000 #12 hours in milliseconds
