server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  datasource:
    #ToDo Remove before commit
    url: jdbc:mysql://localhost:3307/authentication
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  jsonWebToken:
    duration: 43200000 #12 hours in milliseconds
    issuer: "ThreeDeeFilesAuthenticationService"
